version: "3.9"

services:
    app:
        container_name: myBack
        restart: always
        build: ./api
        ports:
            - "5000:5000"
        depends_on:
            - mongo
    client:
        container_name: myFront
        restart: always
        build: ./client
        ports:
            - "80:5173"
        depends_on:
            - app

    mongo:
        container_name: mongo
        restart: always
        image: mongo:latest
        ports:
            - "27017:27017"
