version: "3.8"

services:
    app:
        container_name: myBack
        restart: always
        build: ./api
        ports:
            - "5000:5000"
        depends_on:
            - mongo
    client:
        container_name: myFront
        restart: always
        build: ./client
        ports:
            - "5173:5173"
        depends_on:
            - app

    mongo:
        container_name: mongo
        restart: always
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
