version: '3.8'


services:
  app: 
    build: .
    env_file:
      - .env
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - default




